version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    networks: 
      - apps
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER: pleroma
      - POSTGRES_PASSWORD: pleroma
      - POSTGRES_DB: pleroma
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pleroma:
    build: ./pleroma
    image: pleroma
    restart: always
    command: mix phx.server
    networks: 
      - apps
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/pleroma/uploads
      - ./config:/pleroma/config
      - ./priv:/pleroma/priv

  nginx:
    build: ./nginx
    restart: always
    networks:
      - apps
    depends_on:
      - pleroma
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/srv/letsencrypt:/etc/letsencrypt"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
