version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    networks:
      - back
    expose:
      - "5432"
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pleroma:
    build: ./mypleroma
    image: pleroma
    restart: always
    command: mix phx.server
    networks:
      - back
      - front
    depends_on:
      - postgres
    expose:
      - "4000"
    volumes:
      - ./uploads:/pleroma/uploads
      - ./config:/pleroma/config
      - ./priv:/pleroma/priv

  nginx:
    build: ./nginx
    restart: always
    networks:
      - front
    depends_on:
      - pleroma
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
      - "./nginx/conf:/etc/nginx/conf.d/"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"

networks:
    front:
        external: true
    back:
        external: true
